Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@juanedmr 
juanedmr
/
scaffolding
Public
Cannot fork because you own this repository and are not a member of any organizations.
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
scaffolding/.github/workflows/main.yml
@juanedmr
juanedmr Update main.yml
Latest commit 2bc32c1 3 hours ago
 History
 1 contributor
29 lines (23 sloc)  477 Bytes

name: Python 3.8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint... Checking code lines
      run: |
        make lint
    - name: Test with pytest... testing
      run: |
        make test

    
